# Conda environment for GammaPulsar.
#
# Install:    conda env create -f environment-GammaPulsar-dev.yml
# update:     conda env update -f environment-GammaPulsar-dev.yml
# Activate:   conda activate GammaPulsar
# Deactivate: conda deactivate

name: GammaPulsar

channels:
  - conda-forge
  - fermi
  - sherpa

dependencies:
  # core dependencies
  - python=3.9
  - pip
  - astropy
  - cython
  - gammapy>=1.0
  - fermipy
  - fermitools>=2.2.0
  - numpy>=1.20
  - matplotlib>=3.4
  - scipy!=1.10
  - iminuit>=2.8.0
  - regions>=0.5
  - extension-helpers
  - pip:
      - pint-pulsar
  # extra dependencies
  - ipython
  - jupyter
  - jupyterlab
  - naima
  - pandas
  - sherpa
  - healpy
  # dev dependencies
  - black
  - flake8
  - isort
  - codespell
  - pre-commit
  - setuptools_scm